name: Corlex
version: '1.0-SNAPSHOT'
main: com.devbd1.corlex.Main
api-version: '1.21'
load: STARTUP
authors: [devbd1]
description: Spigot development library, built for the latest version.
website: https://cublex.net
